version: '3'
services:
  dockerapp:
    build: .
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
    depends_on:
      - redis
  redis:
    image: redis:3.2.0
    deploy:
      replicas:2
